### ISSUE TITLE
Build the Pop-up Screen using the pre-built components

### ISSUE THREAD

**Issue by TheoOkafor** [DotCampus/focus-defender#13]
We want to build the pop-up for the extension as designed.

![Image](https://github.com/DotCampus/focus-defender/assets/31534129/efbe4335-b501-442d-aa0e-240769a35505)

### Acceptance Criteria
 - The pop-up should look like the design
 - All the buttons and UI elements should be visible on the pop-up
 - The settings icon should navigate to the options page with the text "extension settings page" on it.

NB: Beyond navigating to a blank, no other functionality is required. i.e. Do not add the block functionality for now.

**Comment by iamstarcode** [comment]
Can I go ahead to do this?

**Comment by iamstarcode** [comment]
Oh! Sorry this has been assigned to someone, my bad!

**Comment by TheoOkafor** [comment]
Yeah@Riri202 is doing it already

**Comment by Riri202** [comment]
Yes. I'm done with it but since we agreed there'll be styling changes, I'm waiting for the final design so I can implement that.
