### ISSUE TITLE
User should be able to Deactivate or Activate the Extension

### ISSUE THREAD

**Issue by DotCampus-Admin** [DotCampus/focus-defender#31]
### Acceptance Criteria

- The Activate/Deactivate button activates or deactivates the extension

**Comment by DotCampus-Admin** [comment]
![Image](https://github.com/DotCampus/focus-defender/assets/140621895/f72084b1-0251-40ad-9765-89ff02200137)

**Comment by Riri202** [comment]
Hi team. Is there a way to implement this feature? I've done some research and what I have found is extensions are activated and deactivated from chrome 'Manage extensions' page and not from within the extension itself.

**Comment by DotCampus-Admin** [comment]
Yeah, @Riri202.

What we can do is add a boolean called `isExtensionActive`. And then check it when we want to block a page. so if `isExtensionActive` is true i.e. the button is activated, we block the page, otherwise, we do not block it.

What do you think?

**Comment by Riri202** [comment]
Okay I think that might work.
