### ISSUE TITLE
Setup ShadCN and Add the needed Atomic Components

### ISSUE THREAD

**Issue by DotCampus-Admin** [DotCampus/focus-defender#7]
We want to use ShadCN for the React components of the Chrome Extension. We will be needing the following Atomic components from ShadCN:

1. Icon Buttons (Delete and Edit, etc.)
2. Buttons (Primary and Secondary buttons)
3. Toggle Switch
4. Alert/Modal component
5. Text Input
6. Select Input
7. etc.

**Comment by DotCampus-Admin** [comment]
Refer to https://www.figma.com/file/6vWLcBu8R8HOAco6KWbCWG/FocusDefender?type=design&node-id=0-1&mode=design&t=y9K9nU7zCjuLjN3I-0 for the Atomic components that we need to add from ShadCN

**Comment by iamstarcode** [comment]
Before we can add Shadcn, we would have to setup the codebase first, and at the first go add the redux for persisting storage, I believe that should, come first, If there is an issue like that, I would be glad to contribute

**Comment by TheoOkafor** [comment]
@iamstarcode Does ShadCN need storage to be in place before we can add its components?

**Comment by iamstarcode** [comment]
Nope, I just could see right now that, there isnt any setup here in the repo.

**Comment by iamstarcode** [comment]
But have seen there is a PR on that, so i'll wait till that is merged.

**Comment by TheoOkafor** [comment]
#1 is merged now

**Comment by iamstarcode** [comment]
Alright, let me for this now
